[package]
name = "cch23-julius"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.0"
ordered-float = { version = "4.1.1", features = ["serde"] }
regex = "1.10.2"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
shuttle-actix-web = "0.34.1"
shuttle-runtime = "0.34.1"
tokio = "1.34.0"
